# Generated by Django 4.2.13 on 2024-07-17 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo do Projeto')),
                ('nome_instituicao', models.CharField(max_length=100, verbose_name='Nome da instituicao')),
                ('cnpj', models.CharField(max_length=15, verbose_name='CNPJ')),
                ('arquivo_projeto', models.FileField(upload_to='projetos', verbose_name='Documento do Projeto')),
                ('data_inicio', models.DateField(verbose_name='Data de inicio')),
                ('data_final', models.DateField(verbose_name='Data de inicio')),
                ('situacao', models.BooleanField(default=False, verbose_name='Situação atual')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projeto.categorias', verbose_name='Categoria')),
            ],
        ),
    ]
