# Generated by Django 5.0.7 on 2024-07-25 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projeto.categorias', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_final',
            field=models.DateField(verbose_name='Data de fim'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome_instituicao',
            field=models.CharField(max_length=100, verbose_name='Nome da instituição'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projetos', to='socios.socio', verbose_name='Participante'),
        ),
    ]
