# Generated by Django 4.2.13 on 2024-07-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_alter_projeto_arquivo_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='arquivo_projeto',
            field=models.FileField(upload_to='static/docs/medias/projetos', verbose_name='Documento do Projeto'),
        ),
    ]
