# Generated by Django 5.0.7 on 2024-07-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_alter_projeto_categoria_alter_projeto_data_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='categoria',
            field=models.CharField(max_length=50, verbose_name='Categoria'),
        ),
    ]
