# Generated by Django 4.2.14 on 2024-07-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0005_alter_projeto_arquivo_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='categoria',
            field=models.CharField(choices=[('Esportes', 'Esportes'), ('Educacao', 'Educação'), ('Cultura', 'Cultura'), ('Pesquisa', 'Pesquisa'), ('Projeto Social', 'Projeto Social'), ('Musica', 'Música'), ('Arte', 'Arte')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
