# Generated by Django 4.2.14 on 2024-07-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0007_alter_projeto_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='data_final',
            field=models.DateField(blank=True, null=True, verbose_name='Data de inicio'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de inicio'),
        ),
    ]
