# Generated by Django 4.2.14 on 2024-07-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0008_alter_projeto_data_final_alter_projeto_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='arquivo_projeto',
            field=models.FileField(upload_to='.projetos', verbose_name='Documento do Projeto'),
        ),
    ]
