# Generated by Django 4.2.14 on 2024-07-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0009_alter_projeto_arquivo_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='arquivo_projeto',
            field=models.FileField(upload_to='projetos/', verbose_name='Documento do Projeto'),
        ),
    ]
