# Generated by Django 4.2.11 on 2024-05-04 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(blank=True, max_length=30, verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, verbose_name='Nome')),
                ('sobrenome', models.CharField(blank=True, max_length=50, verbose_name='Sobrenome')),
                ('cpf', models.CharField(blank=True, max_length=11, verbose_name='CPF')),
                ('dataNascimento', models.DateField(blank=True, verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(blank=True, max_length=10, verbose_name='Sexo')),
                ('registro', models.CharField(blank=True, max_length=11, verbose_name='RG')),
                ('arq_autoDeclaracao', models.FileField(upload_to='declaracoes')),
                ('atividade_agr', models.CharField(blank=True, max_length=4, verbose_name='Mantem atividade agricola na comunidade')),
                ('quantidade_pessoa', models.IntegerField(blank=True, verbose_name='Quantidade de pessoas na familia')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='socios.cargo', verbose_name='Cargo')),
            ],
        ),
    ]
