# Generated by Django 4.2.14 on 2024-07-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='cargo',
            field=models.CharField(max_length=50, verbose_name='Cargo'),
        ),
    ]
