# Generated by Django 4.2.13 on 2024-07-17 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='data_validade',
            field=models.DateField(verbose_name='Mês de Vencimento'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='reference_data',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Mês de cobrança'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='valor',
            field=models.FloatField(default=5.0, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='arq_autoDeclaracao',
            field=models.FileField(upload_to='static/docs/projetos', verbose_name='Auto Declaração'),
        ),
    ]
