# Generated by Django 4.2.14 on 2024-07-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_alter_socio_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='situacao',
            field=models.BooleanField(verbose_name='Situação Atual'),
        ),
    ]
