# Generated by Django 4.2.11 on 2024-05-10 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0003_projeto_situacao'),
        ('socios', '0002_alter_socios_arq_autodeclaracao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socios',
            new_name='Socio',
        ),
    ]
