# Generated by Django 4.2.13 on 2024-05-22 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_mensalidade_socio_delete_socios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socio',
            old_name='nome',
            new_name='nomeCompleto',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='sobrenome',
        ),
    ]
