# Generated by Django 4.2.13 on 2024-07-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_alter_mensalidade_data_validade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='arq_autoDeclaracao',
            field=models.FileField(upload_to='static/docs/medias/projetos', verbose_name='Auto Declaração'),
        ),
    ]
