# Generated by Django 4.2.13 on 2024-07-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_alter_socio_arq_autodeclaracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='arq_autoDeclaracao',
            field=models.FileField(upload_to='socios', verbose_name='Auto Declaração'),
        ),
    ]
