# Generated by Django 4.2.14 on 2024-09-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_alter_socio_situacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
