# Generated by Django 4.2.13 on 2024-05-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_rename_nome_socio_nomecompleto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='dataNascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
