# Generated by Django 4.2.13 on 2024-07-19 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_alter_socio_arq_autodeclaracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='data_validade',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Mês de Vencimento'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
