# Generated by Django 4.2.11 on 2024-05-10 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_socio_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, default='Mensalidade', max_length=50, verbose_name='Descrição')),
                ('valor', models.FloatField(blank=True, verbose_name='Valor')),
                ('refernce_data', models.DateField(blank=True, verbose_name='Mês de cobrança')),
                ('data_validade', models.DateField(blank=True, verbose_name='Mês de Vencimento')),
                ('nome_socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socio')),
            ],
        ),
    ]
