# Generated by Django 4.2.13 on 2024-05-22 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0004_alter_socio_datanascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='data_validade',
            field=models.DateField(blank=True, null=True, verbose_name='Mês de Vencimento'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='descricao',
            field=models.CharField(blank=True, default='Mensalidade', max_length=50, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='reference_data',
            field=models.DateField(blank=True, null=True, verbose_name='Mês de cobrança'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='status',
            field=models.BooleanField(default=False, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='valor',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='arq_autoDeclaracao',
            field=models.FileField(null=True, upload_to='declaracoes', verbose_name='Auto Declaração'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='atividade_agr',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Mantem atividade agricola na comunidade'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='socios.cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='registro',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='sexo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='situacao',
            field=models.BooleanField(default=True, null=True, verbose_name='Situação Atual'),
        ),
    ]
