# Generated by Django 4.2.11 on 2024-05-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0005_mensalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
