# Generated by Django 4.2.14 on 2024-07-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0005_alter_mensalidade_data_validade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensalidade',
            name='data_validade',
            field=models.DateField(verbose_name='Mês de Vencimento'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='reference_data',
            field=models.DateField(verbose_name='Mês de cobrança'),
        ),
    ]
