# Generated by Django 4.2.11 on 2024-05-10 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_mensalidade_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensalidade',
            old_name='refernce_data',
            new_name='reference_data',
        ),
    ]
