# Generated by Django 4.2.14 on 2024-07-24 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0007_alter_mensalidade_data_validade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20, verbose_name='Mês')),
                ('presenca', models.IntegerField(default=0, verbose_name='Presença')),
                ('falta', models.IntegerField(default=0, verbose_name='Falta')),
                ('total', models.IntegerField(default=0, verbose_name='Total')),
                ('nome_socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socio')),
            ],
        ),
    ]
