# Generated by Django 4.2.14 on 2024-07-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0008_frequencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='arq_autoDeclaracao',
            field=models.FileField(upload_to='declaracoes', verbose_name='Auto Declaração'),
        ),
    ]
