# Generated by Django 4.2.11 on 2024-05-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0002_projeto_alter_socioprojeto_projetos_delete_projetos'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='situacao',
            field=models.BooleanField(blank=True, default=False, verbose_name='Situação atual'),
        ),
    ]
