# Generated by Django 4.2.11 on 2024-05-10 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0007_rename_refernce_data_mensalidade_reference_data'),
        ('projetos', '0003_projeto_situacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='participante',
            field=models.ForeignKey(blank=True, default='Socio', on_delete=django.db.models.deletion.DO_NOTHING, related_name='projeto', to='socios.socio', verbose_name='Participante'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='categorias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projetos.categorias', verbose_name='Cargo'),
        ),
    ]
